[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

[font]
size = 13

[terminal]
shell = { program = "/usr/bin/fish", args = []}
